<?php

namespace CDC\Loja\Test;

require './vendor/autoload.php';

use PHPUnit_Framework_TestCase as PHPUnit;

class TestCase extends PHPUnit
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}